import type { Metadata } from "next";
import "@/globals.css";

export const metadata: Metadata = {
  title: {
    template: '%s | MP-5',
    default: 'Home | MP-5',
  },
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
      <html lang="en">
      <body className="min-h-full flex flex-col">
        {children}
      </body>
      </html>
  );
}
